{% set name = "better-optimize" %}
{% set version = "0.1.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/better_optimize-{{ version }}.tar.gz
  sha256: 1d48ca12eb33ab0c469e79add79dfb9be396de988535fea0a69f28ec8e451642

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - numpy
    - setuptools
    - versioneer
    - pip
  run:
    - python >={{ python_min }},<3.13
    - numpy
    - scipy >=1.15
    - rich

test:
  imports:
    - better_optimize
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/jessegrabowski/better_optimize
  summary: A drop-in replacement for scipy optimize functions with quality of life improvements
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jessegrabowski
    - maresb
