{% set name = "better-optimize" %}
{% set version = "0.0.11" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/better_optimize-{{ version }}.tar.gz
  sha256: f3317c31082970030ac204a1fa1a183632a849b8330448231e0a55df0d33ee71

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - numpy
    - setuptools
    - versioneer
    - pip
  run:
    - python >={{ python_min }},<3.13
    - numpy
    - scipy
    - rich

test:
  imports:
    - better_optimize
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/jessegrabowski/better_optimize
  summary: A drop-in replacement for scipy optimize functions with quality of life improvements
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
